@url=http://localhost:8000
@token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAvYXBpL2xvZ2luIiwiaWF0IjoxNzQ1ODQxOTg3LCJleHAiOjE3NDU4NDU1ODcsIm5iZiI6MTc0NTg0MTk4NywianRpIjoieURibXhjdGxWdDlPRUtmSiIsInN1YiI6IjQiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.RRK1fH1ZaYPfYZSfnLJhsz_yqOyUu5uipsPwEofYKXE
### Get request to /home
GET {{url}}/api/home HTTP/1.1
Content-Type: application/json
Accept: application/json

### Register
POST {{url}}/api/register HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "name": "shop",
  "email": "studentjva2@gmail.com",
  "password": "test12345",
  "role":"admin"
  }

### Login 
POST {{url}}/api/login HTTP/1.1
Content-Type: application/json
Accept: application/json

{
   "email": "buyer@gmail.com",
  "password": "test12345"
}

### get users
GET {{url}}/api/users
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

### get user
GET {{url}}/api/users/1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

### update user
PUT {{url}}/api/users/2 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
   "email": "buyer@gmail.com",
  "phone": "123456789",
  "age": 30,
  "role":"buyer"
}

###
GET {{url}}/api/users/services/1000
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}


