@url=http://localhost:8000
@token=lkjllllll

### Get request to /home
GET {{url}}/api/home HTTP/1.1
Content-Type: application/json
Accept: application/json

### Register
POST {{url}}/api/register HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "name": "Rachid2",
  "email": "raherou2@gmail.com",
  "password": "test12345"
}

### Login 
POST {{url}}/api/login HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "email": "raherou@gmail.com",
  "password": "test12345"
}

### get users
GET {{url}}/api/users
Content-Type: application/json
Accept: application/json

### get user
GET {{url}}/api/users/1
Content-Type: application/json
Accept: application/json

### update user
PUT {{url}}/api/users/1 HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "name": "rachid",
  "email": "rachid@example.com",
  "phone": "123456789",
  "age": 30
}


